name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/aws-cicd-pipeline-project || git clone https://github.com/MishaMohammadi/aws-cicd-pipeline-project.git
            cd aws-cicd-pipeline-project
            git pull origin main
            sudo cp index.html /var/www/html/
            sudo cp style.css /var/www/html/
            sudo systemctl restart nginx
